### ISSUE TITLE
Install current version of oskar on jake and elwood

### ISSUE THREAD

**Issue by philusnarh** [radio-astro-debian/oskar-debian#2]
I need an update version of oskar on jake and elwood.

**Comment by o-smirnov** [comment]
Please request things correctly. What you need is a new debian package of oskar corresponding to their latest version. This is what this repo is for.

**Comment by o-smirnov** [comment]
For specific requests on jake and elwood we have this repo: https://github.com/ratt-ru/systems

But in this case the first thing we need is a new oskar package in the PPA, so this is the correct place to ask for it. Also, please include the version number you would like.

**Comment by philusnarh** [comment]
I need a new oskar-debian package (version 2.6.1).

**Comment by gijzelaerr** [comment]
basically this is a duplicate of https://github.com/radio-astro/packaging/issues/18

will try to fix the issue and role a new package.
